window:
  opacity: 0.95
  # opacity: 1.00
  # dim_opacity: 0.85

font:
  normal:
    family: "Rec Mono Linear"
    style: Regular
  bold:
    family: "Rec Mono Linear"
    style: Bold
  italic:
    family: "Rec Mono Linear"
    style: Italic
  bold_italic:
    family: "Rec Mono Linear"
    style: Bold Italic
  size: 12.0

colors:
  # Tokyo Night theme
  primary:
    background: '0x1a1b26'
    foreground: '0xa9b1d6'

  # Normal colors
  normal:
    black:   '0x32344a'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xad8ee6'
    cyan:    '0x449dab'
    white:   '0x787c99'

  # Bright colors
  bright:
    black:   '0x444b6a'
    red:     '0xff7a93'
    green:   '0xb9f27c'
    yellow:  '0xff9e64'
    blue:    '0x7da6ff'
    magenta: '0xbb9af7'
    cyan:    '0x0db9d7'
    white:   '0xacb0d0'

key_bindings:
  - { key: Return, mods: Alt, action: ToggleFullscreen }
  # - { key: Return, mods: Alt, action: ToggleMaximize }
  - { key: T, mods: Alt, command: { program: "sh", args: ["-c", "kill -USR1 $PPID"] } }
